image: python:3.10

variables:
  CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIP_CACHE_DIR: "$CACHE_DIR/pip"
  POETRY_HOME: "$CACHE_DIR/poetry"

before-script:
  script:
    - export PATH="$POETRY_HOME/bin:$PATH"

stages:
  - install-deps
  - build
  - test
workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: always

cache:
    key: poetry-cache
    paths:
      - $CACHE_DIR

install:
  stage: install-deps
  script:
    - pwd
    - ls -la
    - if ! command -v poetry &> /dev/null ; then curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2 ; fi
    - poetry --version
    - poetry install
    - poetry show --outdated


build:
  stage: build
  script:
    - poetry --version
    - echo "Saving Poetry cache..."
    - poetry install
    - poetry build

lint:
  stage: build
  needs: 
    - build
  script:
    - poetry shell
    - pylint src

test:
  stage: test
  needs:
    - lint
  script:
    - poetry shell
    - pytest src
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: on_success
    - when: manual
