image: python:3.10

stages:
  - build
  - test

rules:
- if: $CI_PIPELINE_SOURCE == "merge_request_event"
  when: always

check-dependencies:
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
    - export PATH="/root/.local/bin:$PATH"
  stage: build
  script:
    - poetry install
    - poetry show --outdated
    - poetry build
    - ls -la
  artifacts:
    paths:
      - $HOME/.cache/pypoetry/virtualenvs


lint-job:
  stage: build
  script:
    - pip install pylint
    - pylint src

test-job:
  stage: test
  needs:
    - check-dependencies
  allow_failure: true
  script:
    - poetry install
    - poetry build
    - pytest src
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: on_success
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "main"
      when: manual
