image: python:3.10

stages:
  - build
  - test

check-dependencies:
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
    - export PATH="/root/.local/bin:$PATH"
  stage: build
  script:
    - poetry install
    - poetry show --outdated
    - poetry run safety check
    - ls -la
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
  artifacts:
    paths:
      - $HOME/.cache/pypoetry/virtualenvs

lint-job:
  stage: build
  script:
    - pip install pylint
    - pylint src
  rules:
  - if: '$CI_MERGE_REQUEST_ID'
    when: always

test-job:
  stage: test
  needs:
    - check-dependencies
  allow_failure: true
  script:
    - poetry install
    - poetry build
    - pytest src