image: python:3.10

stages:
  - check-deps
  - build
  - test
workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    when: always


cache:
    key: poetry-cache
    paths:
      - $HOME/.cache/pypoetry
      - /root/.local/bin
    policy: pull

install-dependencies:
  script:
    - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
    - export PATH="/root/.local/bin:$PATH"
  stage: check-deps
  when: manual
  allow_failure: true
  cache:
    key: poetry-cache
    paths:
      - $HOME/.cache/pypoetry
      - /root/.local/bin
    policy: push


build-job:
  stage: build
  script:
    - poetry install
    - poetry show --outdated
    - poetry build
    - ls -la

lint-job:
  stage: build
  needs: 
    - build-job
  script:
    - pip install pylint
    - pylint src

test-job:
  stage: test
  needs:
    - lint-job
  script:
    - poetry install
    - poetry build
    - pytest src
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: on_success
    - when: manual
