image: python:3.10

stages:
  - build
  - test

check_dependencies:
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
  stage: build
  script:
    - poetry install
    - poetry show --outdated
    - poetry run safety check
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: always

lint-job:
  stage: build
  script:
    - pip install pylint
    - pylint src
  rules:
  - if: '$CI_MERGE_REQUEST_ID'
    when: always

test-job:
  stage: test
  allow_failure: true
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
  script:
    - poetry install
    - poetry build
    - pytest src